version: '3.7'
# docker build -t  ./
# docker stack deploy --compose-file docker-stack.yml dugout
services:
  dugout-crawler:
    image: dugout-crawler:latest
    networks:
      - swarm_network
      - default
    env_file:
      - .env
    configs:
      - source: dugout_config
        target: /dugout-crawler/config.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == tool
configs:
  dugout_config:
    name: dugout_config-0
    file: ./config.json

networks:
  swarm_network:
    driver: overlay
    external: true
