version: '3.7'
# docker build -t  ./
# docker stack deploy --compose-file docker-stack.yml dugout
services:
  dugout-backup:
    image: dugout-backup:latest
    networks:
      - swarm_network
      - default
    env_file:
      - .env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == tool

networks:
  swarm_network:
    driver: overlay
    external: true
